name: syncthing
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:v2.1.3-ls228@sha256:9e9b931bf48a8a08bffaaa7e2fc2b7d0126b02def2bf1d3395d9b531817f9af3
    container_name: syncthing
    volumes:
      - ${DATA_DIR}/syncthing:/config
      - ${DATA_DIR}/code:/code
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    ports:
      - '0.0.0.0:21027:21027/udp'
      - '0.0.0.0:22000:22000/tcp'
      - '0.0.0.0:22000:22000/udp'
    restart: unless-stopped
    labels:
      readme.description: Free and open source peer-to-peer file synchronization
      readme.links.web: https://syncthing.net/
      traefik.enable: true
      traefik.http.routers.syncthing.entrypoints: https
      traefik.http.routers.syncthing.rule: Host(`syncthing.${HOST}`)
      traefik.http.routers.syncthing.tls.certresolver: resolver
      traefik.http.services.syncthing.loadbalancer.server.port: 8384
    hostname: ${HOST}
