name: github
services:
  barbie-github-runner:
    image: myoung34/github-runner:2.327.0@sha256:9c8390f6b646f068cdaf2d8ef16b0b22ab096a72a649f698b41597d8adda98b1
    container_name: barbie-github-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/barbie-github-runner/data:/runner/data
    environment:
      LABELS: linux,x64
      REPO_URL: https://github.com/ben-pearce/barbie-server-deployment/
      RUNNER_NAME: barbie-runner
      RUNNER_SCOPE: repo
    env_file:
      - ../.secrets/github_runner_token
    restart: unless-stopped
    security_opt:
      - label:disable
  etch-github-runner:
    image: myoung34/github-runner:2.327.0@sha256:9c8390f6b646f068cdaf2d8ef16b0b22ab096a72a649f698b41597d8adda98b1
    container_name: etch-github-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/etch-github-runner/data:/runner/data
    environment:
      LABELS: linux,x64
      REPO_URL: https://github.com/ben-pearce/etch-server-deployment/
      RUNNER_NAME: etch-runner
      RUNNER_SCOPE: repo
    env_file:
      - ../.secrets/github_runner_token
    restart: unless-stopped
    security_opt:
      - label:disable
  jessie-github-runner:
    image: myoung34/github-runner:2.327.0@sha256:9c8390f6b646f068cdaf2d8ef16b0b22ab096a72a649f698b41597d8adda98b1
    container_name: jessie-github-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/jessie-github-runner/data:/runner/data
    environment:
      LABELS: linux,x64
      REPO_URL: https://github.com/ben-pearce/jessie-server-deployment/
      RUNNER_NAME: jessie-runner
      RUNNER_SCOPE: repo
    env_file:
      - ../.secrets/github_runner_token
    restart: unless-stopped
    security_opt:
      - label:disable
  rc-github-runner:
    image: myoung34/github-runner:2.327.0@sha256:9c8390f6b646f068cdaf2d8ef16b0b22ab096a72a649f698b41597d8adda98b1
    container_name: rc-github-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/rc-github-runner/data:/runner/data
    environment:
      LABELS: linux,x64
      REPO_URL: https://github.com/ben-pearce/rc-server-deployment/
      RUNNER_NAME: rc-runner
      RUNNER_SCOPE: repo
    env_file:
      - ../.secrets/github_runner_token
    restart: unless-stopped
    security_opt:
      - label:disable
  sparks-github-runner:
    image: myoung34/github-runner:2.327.0@sha256:9c8390f6b646f068cdaf2d8ef16b0b22ab096a72a649f698b41597d8adda98b1
    container_name: sparks-github-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/sparks-github-runner/data:/runner/data
    environment:
      LABELS: linux,x64
      REPO_URL: https://github.com/ben-pearce/sparks-server-deployment/
      RUNNER_NAME: sparks-runner
      RUNNER_SCOPE: repo
    env_file:
      - ../.secrets/github_runner_token
    restart: unless-stopped
    profiles:
      - github-runner
    security_opt:
      - label:disable
  woody-github-runner:
    image: myoung34/github-runner:2.327.0@sha256:9c8390f6b646f068cdaf2d8ef16b0b22ab096a72a649f698b41597d8adda98b1
    container_name: woody-github-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/woody-github-runner/data:/runner/data
    environment:
      LABELS: linux,x64
      REPO_URL: https://github.com/ben-pearce/woody-server-deployment/
      RUNNER_NAME: woody-runner
      RUNNER_SCOPE: repo
    env_file:
      - ../.secrets/github_runner_token
    restart: unless-stopped
    security_opt:
      - label:disable
  zurg-github-runner:
    image: myoung34/github-runner:2.327.0@sha256:9c8390f6b646f068cdaf2d8ef16b0b22ab096a72a649f698b41597d8adda98b1
    container_name: zurg-github-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/zurg-github-runner/data:/runner/data
    environment:
      LABELS: linux,x64
      REPO_URL: https://github.com/ben-pearce/zurg-server-deployment/
      RUNNER_NAME: zurg-runner
      RUNNER_SCOPE: repo
    env_file:
      - ../.secrets/github_runner_token
    restart: unless-stopped
    security_opt:
      - label:disable
