name: syncthing
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:v2.1.5-ls229@sha256:455bb8427106eb8522f9133a43d4e6ca799d4983c1b53e77a2bc6f7290855483
    container_name: syncthing
    volumes:
      - ${DATA_DIR}/syncthing:/config
      - ${DATA_DIR}/code:/code
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    ports:
      - '0.0.0.0:21027:21027/udp'
      - '0.0.0.0:22000:22000/tcp'
      - '0.0.0.0:22000:22000/udp'
    restart: unless-stopped
    labels:
      readme.description: Free and open source peer-to-peer file synchronization
      readme.links.web: https://syncthing.net/
      traefik.enable: true
      traefik.http.routers.syncthing.entrypoints: https
      traefik.http.routers.syncthing.rule: Host(`syncthing.${HOST}`)
      traefik.http.routers.syncthing.tls.certresolver: resolver
      traefik.http.services.syncthing.loadbalancer.server.port: 8384
    hostname: ${HOST}
