name: syncthing
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:v2.0.16-ls215@sha256:6a5f5d3412f80539289cee9bd0a6df9645f8540ecaed7d34f1bd0930bfd8c55e
    container_name: syncthing
    volumes:
      - ${DATA_DIR}/syncthing:/config
      - ${DATA_DIR}/code:/code
    environment:
      - PUID
      - PGID
      - TZ
    ports:
      - '0.0.0.0:21027:21027/udp'
      - '0.0.0.0:22000:22000/tcp'
      - '0.0.0.0:22000:22000/udp'
    restart: unless-stopped
    labels:
      readme.description: Free and open source peer-to-peer file synchronization
      readme.links.web: https://syncthing.net/
      traefik.enable: true
      traefik.http.routers.syncthing.entrypoints: https
      traefik.http.routers.syncthing.rule: Host(`syncthing.${HOST}`)
      traefik.http.routers.syncthing.tls.certresolver: resolver
      traefik.http.services.syncthing.loadbalancer.server.port: 8384
    hostname: ${HOST}
