services:
  barbie-github-runner:
    container_name: barbie-github-runner
    env_file:
      - ../.secrets/github_runner_token
    environment:
      LABELS: linux,x64
      REPO_URL: https://github.com/ben-pearce/barbie-server-deployment/
      RUNNER_NAME: barbie-runner
      RUNNER_SCOPE: repo
    image: myoung34/github-runner:2.322.0
    security_opt:
      - label:disable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/barbie-github-runner/data:/runner/data
  jessie-github-runner:
    container_name: jessie-github-runner
    env_file:
      - ../.secrets/github_runner_token
    environment:
      LABELS: linux,x64
      REPO_URL: https://github.com/ben-pearce/jessie-server-deployment/
      RUNNER_NAME: jessie-runner
      RUNNER_SCOPE: repo
    image: myoung34/github-runner:2.322.0
    security_opt:
      - label:disable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/jessie-github-runner/data:/runner/data
  sparks-github-runner:
    container_name: sparks-github-runner
    env_file:
      - ../.secrets/github_runner_token
    environment:
      LABELS: linux,x64
      REPO_URL: https://github.com/ben-pearce/sparks-server-deployment/
      RUNNER_NAME: sparks-runner
      RUNNER_SCOPE: repo
    image: myoung34/github-runner:2.322.0
    profiles:
      - github-runner
    security_opt:
      - label:disable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/sparks-github-runner/data:/runner/data
